// Scans skills/*.md, parses each file's frontmatter, and writes
// src/registry.generated.ts containing the frontmatter array. The Worker
// imports this at build time — no runtime manifest fetch needed.
//
// Skill *bodies* are not bundled; they live as Static Assets and are
// fetched via env.ASSETS.fetch('/<id>.md') on demand.
//
// Run via `bun run build-registry` (also invoked automatically by
// `bun run dev` and `bun run deploy` through package.json).

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseSkill, type Frontmatter } from '../src/frontmatter'

const skillsDir = './skills'
const out = './src/registry.generated.ts'

const files = readdirSync(skillsDir)
  .filter((f) => f.endsWith('.md'))
  .sort()

if (files.length === 0) {
  throw new Error(`no skill files found under ${skillsDir}`)
}

const manifest: Frontmatter[] = files.map((f) => {
  const id = f.replace(/\.md$/, '')
  const source = readFileSync(join(skillsDir, f), 'utf-8')
  const { frontmatter } = parseSkill(source)
  if (frontmatter.id !== id) {
    throw new Error(`id mismatch: skills/${f} declares id "${frontmatter.id}"`)
  }
  return frontmatter
})

const content = `// AUTO-GENERATED by scripts/build-registry.ts. Do not edit.
// To add a skill, drop a new file at skills/<id>.md and rerun \`bun run build-registry\`.
import type { Frontmatter } from './frontmatter'

export const manifest: Frontmatter[] = ${JSON.stringify(manifest, null, 2)}
`

writeFileSync(out, content)
console.log(`wrote ${out} with ${manifest.length} skill(s)`)
