// Scans skills/*/SKILL.md (the layout the `npx skills add` CLI from
// vercel-labs/skills expects), parses each file's frontmatter, and writes
// src/registry.generated.ts containing the frontmatter array. The Worker
// imports this at build time — no runtime manifest fetch needed.
//
// Skill *bodies* are not bundled; they live as Static Assets and are
// fetched via env.ASSETS.fetch('/<name>/SKILL.md') on demand.
//
// Run via `bun run build-registry` (also invoked automatically by
// `bun run dev` and `bun run deploy` through package.json).

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseSkill, type Frontmatter } from '../src/frontmatter'

const skillsDir = './skills'
const out = './src/registry.generated.ts'

const entries = readdirSync(skillsDir).filter((entry) => {
  const path = join(skillsDir, entry)
  return statSync(path).isDirectory()
})

if (entries.length === 0) {
  throw new Error(`no skill directories found under ${skillsDir}`)
}

const manifest: Frontmatter[] = entries.sort().map((name) => {
  const skillFile = join(skillsDir, name, 'SKILL.md')
  const source = readFileSync(skillFile, 'utf-8')
  const { frontmatter } = parseSkill(source)
  if (frontmatter.name !== name) {
    throw new Error(`name mismatch: ${skillFile} declares name "${frontmatter.name}"`)
  }
  return frontmatter
})

const content = `// AUTO-GENERATED by scripts/build-registry.ts. Do not edit.
// To add a skill, drop a new file at skills/<name>/SKILL.md and rerun \`bun run build-registry\`.
import type { Frontmatter } from './frontmatter'

export const manifest: Frontmatter[] = ${JSON.stringify(manifest, null, 2)}
`

writeFileSync(out, content)
console.log(`wrote ${out} with ${manifest.length} skill(s)`)
